"""unique constraint on chunks (doc_id, strategy, ordinal)

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-20 02:45:51.137785

Gives Phase 2 a stable natural key for "ground-truth chunk ids" in the golden set:
`chunk_id` is a serial PK and `replace_chunks()` (clause.db.repository) is
delete-then-insert, so every ingest renumbers every chunk. This constraint also
turns a failed/partial delete in `replace_chunks()` into a loud duplicate-key error
instead of silently doubling rows. See final whole-branch review, FIX 6.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chunks_doc_strategy_ordinal', 'chunks', ['doc_id', 'strategy', 'ordinal'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chunks_doc_strategy_ordinal', 'chunks', type_='unique')
    # ### end Alembic commands ###
